// src/constants/icons.js

import { 
    LucideSend, LucideSettings, LucideBookCopy, LucideUsers, LucideFeather, 
    LucideRefreshCw, LucidePlusCircle, LucidePlus, LucideTrash2, LucideStar, 
    LucideSave, LucideLibrary, LucideSparkles, LucideZap, LucidePlayCircle, 
    LucideEdit, LucideX, LucideBrainCircuit, LucideMenu, LucideSun, LucideMoon,
    LucideClock, LucideCloud, LucideCloudRain, LucideCloudSnow, LucideCloudFog,
    LucideFileText, LucideMemoryStick, LucideBookOpen, LucideMessageSquare,
    LucideBookUser, LucideGlobe, LucideChevronDown, LucideChevronRight, 
    LucideBrainCog, LucideHeartHandshake, LucideDrama, LucideEyeOff, LucideMessageCircle,
    LucideUserCog, LucideBot, LucideFileArchive, LucideCpu, LucideShare2, LucideImage,
    LucideCalendarDays,
    LucideInfo,
    LucideAlertCircle,
    LucideCheckCircle,
    LucideAlertTriangle,
    LucideArchiveX,
    LucideUserX,
    LucidePin,
    LucidePinOff,
    LucideCopy,
    LucideChevronUp,
    LucideColumns,
    LucideMessageCircle as LucideChat,
    LucideTag,
    LucideGripVertical,
    LucideCode,
    LucideClipboardList,
    LucideTheater,
    LucideUser,
    LucideHeart,
    LucideCoffee,
    LucideShield,
    LucideHeartPulse,
    LucideSwords,
    LucideHome,
    LucideArchive,
    LucideSmilePlus,
    LucideMonitor,
    // [FEATURE] 페르소나 설정 내보내기용 아이콘 추가
    LucideFileDown,
} from 'lucide-react';

export const ICONS = {
    LucideSend, LucideSettings, LucideBookCopy, LucideUsers, LucideFeather, 
    LucideRefreshCw, LucidePlusCircle, LucidePlus, LucideTrash2, LucideStar, 
    LucideSave, LucideLibrary, LucideSparkles, LucideZap, LucidePlayCircle, 
    LucideEdit, LucideX, LucideBrainCircuit, LucideMenu, LucideSun, LucideMoon,
    LucideClock, LucideCloud, LucideCloudRain, LucideCloudSnow, LucideCloudFog,
    LucideFileText, LucideMemoryStick, LucideBookOpen, LucideMessageSquare,
    LucideBookUser, LucideGlobe, LucideChevronDown, LucideChevronRight, 
    LucideBrainCog, LucideHeartHandshake, LucideDrama, LucideEyeOff, LucideMessageCircle,
    LucideUserCog, LucideBot, LucideFileArchive, LucideCpu, LucideShare2, LucideImage,
    LucideCalendarDays,
    LucideInfo,
    LucideAlertCircle,
    LucideCheckCircle,
    LucideAlertTriangle,
    LucideArchiveX,
    LucideUserX,
    LucidePin,
    LucidePinOff,
    LucideCopy,
    LucideChevronUp,
    LucideColumns,
    LucideChat,
    LucideTag,
    LucideGripVertical,
    LucideCode,
    LucideClipboardList,
    LucideTheater,
    LucideUser,
    LucideHeart,
    LucideCoffee,
    LucideShield,
    LucideHeartPulse,
    LucideSwords,
    LucideHome,
    LucideArchive,
    LucideSmilePlus,
    LucideMonitor,
    // [FEATURE] 페르소나 설정 내보내기용 아이콘 추가
    LucideFileDown,
};